"""Integrated Systematic Execution Engine & Quantitative Microstructure Backtester.

Implements:
  1. Microstructure Decision Hierarchy:
     - Positive Gamma Regime Protocol: Asymmetric Statistical Mean-Reversion Engine
     - Negative Gamma Regime Protocol: Kinematic Breakout & Liquidity Cascade Engine
     - 0DTE Charm Drift Override (post-14:00 EST afternoon unhedging tailwinds)

  2. Realistic Event-Driven Intraday/Daily Backtesting Simulator:
     - Point-in-time sequential bar processing
     - Realistic slippage, bid-ask spread models, and transaction costs
     - Dynamic trailing stops anchored to latent price state and kernel envelopes
     - Overnight memory resets and OPEX expiration handling
     - Complete performance reporting: Sharpe, Sortino, Max Drawdown, Gamma P&L attribution,
       Delta Hedging P&L, Win Rate, Expectancy, and Regime-Segmented Tearsheet.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, field
import math
from typing import Any, Mapping, Sequence

import numpy as np
import pandas as pd

from edge.research.microstructure_regime import (
    MicrostructureRegimeSnapshot,
    compute_microstructure_regime,
)
from edge.research.state_estimation import (
    NadarayaWatsonEnvelopeResult,
    KinematicKalmanResult,
    AnchoredVWAPResult,
    causal_nadaraya_watson_envelope,
    kinematic_kalman_filter,
    compute_anchored_vwap,
)


# ---------------------------------------------------------------------------
# Signal & Execution Structs
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ExecutionSignal:
    """Actionable execution ticket generated by the microstructure engine."""
    bar_index: int
    timestamp: str
    symbol: str
    action: str             # "ENTER_LONG" | "ENTER_SHORT" | "EXIT_LONG" | "EXIT_SHORT" | "HOLD" | "NONE"
    direction: str          # "long" | "short" | "flat"
    price: float
    regime: str             # "positive_gamma" | "negative_gamma" | "neutral_transition" | "gamma_unmeasured"
    topography_quadrant: str
    setup_name: str         # e.g. "PosGEX_LowerBand_Exhaustion", "NegGEX_PutWall_Cascade", "0DTE_Charm_MeltUp"
    conviction: float       # 0.0 to 1.0
    suggested_size_pct: float
    entry_price: float
    stop_loss: float
    take_profit: float
    invalidation_anchor: str
    kalman_velocity: float
    kalman_zscore: float
    kernel_mean: float
    upper_envelope: float
    lower_envelope: float
    anchored_vwap: float
    #: None whenever no dealer-gamma series was supplied for this bar. The
    #: engine previously substituted s_t * 1.025 / 0.975 / 0.985 here, so a
    #: signal ticket displayed three precise-looking structural levels that
    #: were fixed percentages of the bar's own close.
    call_wall: float | None
    put_wall: float | None
    gamma_flip: float | None
    #: One-bar 1-sigma move in dollars -- the unit every stop and target below
    #: is quoted in. Stops used to be multiples of ``sigma_local``, which is the
    #: kernel-weighted dispersion of price *levels* over a 150-bar window, not a
    #: per-bar volatility: on CRDO that is $29 against a $9 implied daily move,
    #: so a "1.5 sigma" stop sat 26% away and the 3-sigma target implied a 52%
    #: move by tomorrow. It priced the width of the trend, not the risk of the bar.
    risk_unit: float = 0.0
    #: "implied_1bar" | "atr" | "close_to_close" -- which measurement produced it.
    risk_unit_basis: str = "none"
    #: Reward-to-risk of the quoted plan, |target - entry| / |entry - stop|.
    risk_reward: float = 0.0
    #: Scale-out ladder at 1R/2R/3R off the same unit.
    target_1r: float = 0.0
    target_2r: float = 0.0
    target_3r: float = 0.0
    notes: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class SimulatedTrade:
    """A completed or active round-trip simulated trade."""
    trade_id: int
    symbol: str
    direction: str          # "long" | "short"
    regime: str
    setup_name: str
    entry_bar: int
    entry_time: str
    entry_price: float
    exit_bar: int | None
    exit_time: str | None
    exit_price: float | None
    exit_reason: str | None # "take_profit" | "stop_loss" | "invalidation" | "velocity_flip" | "session_close"
    shares: float
    gross_pnl: float
    net_pnl: float
    return_pct: float
    holding_bars: int
    slippage_cost: float
    transaction_cost: float
    gamma_pnl_attribution: float
    delta_hedge_cost: float


@dataclass(frozen=True)
class RegimeMetrics:
    """Performance breakdown for a single microstructure regime."""
    regime_name: str
    n_trades: int
    win_rate: float
    profit_factor: float
    total_net_pnl: float
    avg_return_pct: float
    sharpe_ratio: float


@dataclass(frozen=True)
class BacktestTearsheet:
    """Comprehensive performance report from systematic microstructure backtest."""
    symbol: str
    n_bars: int
    start_date: str
    end_date: str
    initial_capital: float
    ending_capital: float
    total_net_pnl: float
    total_return_pct: float
    cagr_pct: float
    sharpe_ratio: float
    sortino_ratio: float
    calmar_ratio: float
    max_drawdown_pct: float
    max_drawdown_dollar: float
    win_rate: float
    profit_factor: float
    expectancy_per_trade: float
    total_trades: int
    winning_trades: int
    losing_trades: int
    avg_win_dollar: float
    avg_loss_dollar: float
    win_loss_ratio: float
    avg_holding_bars: float
    total_slippage: float
    total_commissions: float
    total_gamma_pnl: float
    total_hedging_pnl: float
    daily_turnover_pct: float
    equity_curve: list[dict[str, Any]]
    drawdown_curve: list[dict[str, Any]]
    trades: list[SimulatedTrade]
    regime_breakdown: dict[str, RegimeMetrics]


#: Hard ceiling on notional in a single name, as a percentage of capital.
MAX_SINGLE_NAME_PCT = 10.0


# ---------------------------------------------------------------------------
# Bar Volatility Unit
# ---------------------------------------------------------------------------

def compute_bar_volatility_unit(
    prices: Sequence[float] | np.ndarray,
    *,
    highs: Sequence[float] | np.ndarray | None = None,
    lows: Sequence[float] | np.ndarray | None = None,
    iv_series: Sequence[float] | np.ndarray | None = None,
    atr_period: int = 14,
    bars_per_year: float = 252.0,
) -> tuple[np.ndarray, str]:
    """One-bar 1-sigma move, in dollars, for sizing stops and targets.

    This is deliberately *not* ``NadarayaWatsonEnvelopeResult.sigma_local``.
    That quantity is the kernel-weighted standard deviation of price levels
    around the causal trend over a long lookback -- it measures how wide the
    trend channel is, and on a name that has travelled far it is several times
    the size of one bar's actual range. Stops and targets need the risk of the
    next bar, which is what this returns.

    Basis, in order of preference:
      1. ``implied_1bar``   -- S * IV / sqrt(bars_per_year). Forward-looking and
         identical to the Rule-of-16 expected move the desk displays, so the
         ticket and the expected-move corridor are quoted off one number.
      2. ``atr``            -- Wilder ATR over true range. Needs highs/lows.
      3. ``close_to_close`` -- EWMA standard deviation of log returns * price.

    Returns:
        (unit_series, basis_label). Every element is floored at 0.25% of price
        so a flat stretch cannot produce a zero-width stop.
    """
    p = np.asarray(prices, dtype=float)
    n = len(p)
    if n == 0:
        return np.array([], dtype=float), "none"

    floor = 0.0025 * np.abs(p)

    iv = np.asarray(iv_series, dtype=float) if iv_series is not None and len(iv_series) == n else None
    if iv is not None and np.isfinite(iv).any() and np.nanmax(iv) > 0:
        iv_dec = np.where(iv > 1.5, iv / 100.0, iv)  # accept 88.0 or 0.88
        unit = np.abs(p) * iv_dec / math.sqrt(max(1.0, bars_per_year))
        unit = np.where(np.isfinite(unit) & (unit > 0), unit, floor)
        return np.maximum(unit, floor), "implied_1bar"

    hi = np.asarray(highs, dtype=float) if highs is not None and len(highs) == n else None
    lo = np.asarray(lows, dtype=float) if lows is not None and len(lows) == n else None
    if hi is not None and lo is not None and np.isfinite(hi).all() and np.isfinite(lo).all():
        prev_close = np.concatenate(([p[0]], p[:-1]))
        tr = np.maximum(hi - lo, np.maximum(np.abs(hi - prev_close), np.abs(lo - prev_close)))
        # Wilder smoothing, strictly causal.
        atr = np.empty(n, dtype=float)
        seed = min(atr_period, n)
        atr[:seed] = np.cumsum(tr[:seed]) / np.arange(1, seed + 1)
        for t in range(seed, n):
            atr[t] = (atr[t - 1] * (atr_period - 1) + tr[t]) / atr_period
        return np.maximum(atr, floor), "atr"

    # Close-to-close fallback: EWMA of squared log returns (lambda = 0.94).
    unit = np.empty(n, dtype=float)
    if n < 2:
        return floor, "close_to_close"
    rets = np.diff(np.log(np.maximum(p, 1e-9)))
    lam = 0.94
    var = float(rets[0] ** 2)
    unit[0] = unit[1] = math.sqrt(var) * abs(p[0])
    for t in range(1, n - 1):
        var = lam * var + (1.0 - lam) * float(rets[t] ** 2)
        unit[t + 1] = math.sqrt(max(var, 1e-12)) * abs(p[t + 1])
    return np.maximum(unit, floor), "close_to_close"


# ---------------------------------------------------------------------------
# Systematic Signal Generation Engine
# ---------------------------------------------------------------------------

def generate_microstructure_signals(
    prices: Sequence[float] | np.ndarray,
    *,
    timestamps: Sequence[str] | None = None,
    symbol: str = "SPY",
    volumes: Sequence[float] | np.ndarray | None = None,
    highs: Sequence[float] | np.ndarray | None = None,
    lows: Sequence[float] | np.ndarray | None = None,
    gamma_flip_series: Sequence[float] | np.ndarray | None = None,
    call_wall_series: Sequence[float] | np.ndarray | None = None,
    put_wall_series: Sequence[float] | np.ndarray | None = None,
    net_gex_series: Sequence[float] | np.ndarray | None = None,
    net_chex_series: Sequence[float] | np.ndarray | None = None,
    iv_series: Sequence[float] | np.ndarray | None = None,
    base_bandwidth: float = 20.0,
    envelope_alpha: float = 2.0,
    kalman_sigma_q: float = 1e-3,
    kalman_sigma_r: float = 1.0,
    breakout_z: float = 1.6,
    exhaustion_z: float = 0.4,
    enable_0dte_charm_override: bool = True,
) -> tuple[list[ExecutionSignal], NadarayaWatsonEnvelopeResult, KinematicKalmanResult, list[AnchoredVWAPResult]]:
    """Evaluate full microstructure decision hierarchy across bars to produce actionable execution signals.

    Decision Rules:
      1. Positive Gamma Regime (S_t > S* and GEX_net > 0):
         - Long: S_t <= Lower Envelope, S_t > Put Wall, Kalman z-score >= -exhaustion_z (exhaustion of downside momentum)
         - Short: S_t >= Upper Envelope, S_t <= Call Wall * 1.002, Kalman z-score <= +exhaustion_z (upside deceleration)
         - Invalidation: S_t crosses below S* on accelerating velocity (z_v < -1.5)
         - 0DTE Charm: If enabled and post-14:00 with CHEX > 0, suppress short signals and extend long targets

      2. Negative Gamma Regime (S_t < S* and GEX_net < 0):
         - Short Breakdown: S_t breaches Put Wall, S_t < VWAP, lower envelope expands down, z_v < -breakout_z
         - Long Short-Squeeze: S_t breaks above Call Wall, upper envelope expands up, z_v > +breakout_z
         - Invalidation: False breakout re-crossing S*

    Returns:
        Tuple of (signals_list, nw_result, kalman_result, vwap_results)
    """
    p = np.asarray(prices, dtype=float)
    n = len(p)
    if n == 0:
        empty_nw = NadarayaWatsonEnvelopeResult(np.array([]), np.array([]), np.array([]), np.array([]), np.array([]), np.array([]))
        empty_k = KinematicKalmanResult(np.array([]), np.array([]), np.array([]), np.array([]), np.array([]), np.array([]), np.array([]), np.array([]), np.array([]), np.array([], dtype=bool), np.array([], dtype=bool))
        return [], empty_nw, empty_k, []

    v = np.asarray(volumes, dtype=float) if volumes is not None and len(volumes) == n else np.ones(n, dtype=float)
    ts_list = list(timestamps) if timestamps is not None and len(timestamps) == n else [f"Bar_{i}" for i in range(n)]

    # 1. State Estimation Calculations
    nw_res = causal_nadaraya_watson_envelope(
        p,
        base_bandwidth=base_bandwidth,
        alpha=envelope_alpha,
        gex_series=net_gex_series,
        use_dynamic_bandwidth=True,
    )

    kalman_res = kinematic_kalman_filter(
        p,
        dt=1.0,
        base_sigma_q=kalman_sigma_q,
        sigma_r=kalman_sigma_r,
        iv_series=iv_series,
        gex_series=net_gex_series,
        breakout_z=breakout_z,
        exhaustion_z=exhaustion_z,
    )

    # Risk unit: the one-bar 1-sigma move that every stop and target is quoted
    # in. Kept separate from the envelope's sigma_local, which measures channel
    # width over a long lookback and is not a per-bar risk figure.
    risk_units, risk_basis = compute_bar_volatility_unit(
        p, highs=highs, lows=lows, iv_series=iv_series
    )

    # Microstructure Anchored VWAP (anchors at bar 0 and whenever spot crosses gamma flip)
    flip_crossings = [0]
    if gamma_flip_series is not None and len(gamma_flip_series) == n:
        for t in range(1, n):
            prev_s = p[t - 1]
            curr_s = p[t]
            flip = gamma_flip_series[t]
            if (prev_s < flip <= curr_s) or (prev_s > flip >= curr_s):
                flip_crossings.append(t)
    # Keep bar 0 (the window anchor) plus the four MOST RECENT flip crossings,
    # not the oldest. `sorted(set(...))[:5]` kept the five oldest crossings
    # and silently dropped every recent one -- on any window with more than
    # five crossings the anchors shown were stale by construction, discarding
    # exactly the regime changes closest to the current bar that a trader
    # would care about.
    flip_crossings = sorted(set(flip_crossings))
    recent_crossings = [c for c in flip_crossings if c != 0][-4:]
    flip_crossings = sorted({0, *recent_crossings})
    anchor_names = [
        "Session_Open" if c == 0 else f"Flip_Cross_Bar_{c}" for c in flip_crossings
    ]

    vwap_results = compute_anchored_vwap(p, v, flip_crossings, anchor_names)
    primary_vwap = vwap_results[0].vwap if vwap_results else p

    # 2. Sequential Signal Generation
    signals: list[ExecutionSignal] = []

    for t in range(n):
        s_t = p[t]
        s_prev = p[t - 1] if t > 0 else s_t
        ts = ts_list[t]

        # Structural levels are used only when they were actually supplied.
        # Falling back to fixed percentages of the current close manufactured a
        # "gamma flip" that was, by construction, always 1.5% below spot -- so
        # every bar read as positive gamma and the regime branch below was
        # decided by arithmetic on the price rather than by dealer positioning.
        has_gamma = (
            gamma_flip_series is not None and len(gamma_flip_series) == n
            and net_gex_series is not None and len(net_gex_series) == n
        )
        flip = float(gamma_flip_series[t]) if has_gamma else None
        c_wall = float(call_wall_series[t]) if call_wall_series is not None and len(call_wall_series) == n else None
        p_wall = float(put_wall_series[t]) if put_wall_series is not None and len(put_wall_series) == n else None
        net_gex = float(net_gex_series[t]) if has_gamma else None
        net_chex = net_chex_series[t] if net_chex_series is not None and len(net_chex_series) == n else 0.0

        upper_band = nw_res.upper[t]
        lower_band = nw_res.lower[t]
        k_mean = nw_res.mean[t]
        prev_low_band = nw_res.lower[t - 1] if t > 0 else lower_band
        prev_up_band = nw_res.upper[t - 1] if t > 0 else upper_band
        vwap_t = primary_vwap[t] if not np.isnan(primary_vwap[t]) else s_t
        v_k = kalman_res.velocity[t]
        v_z = kalman_res.velocity_zscore[t]
        v_prev_z = kalman_res.velocity_zscore[t - 1] if t > 0 else v_z
        sigma_loc = max(0.5, nw_res.sigma_local[t])
        # Stops and targets are quoted in `u`, never in sigma_loc.
        u = float(max(1e-6, risk_units[t]))

        # Trend estimation from causal kernel mean
        lag_k = max(0, t - 5)
        trend_up = k_mean >= nw_res.mean[lag_k]

        # Topography Quadrant.
        #
        # With no gamma data the engine does not guess at a gamma regime. It
        # falls back to the price-structure analogue of the same question --
        # is the tape extending or reverting -- read off the Kalman velocity
        # z-score, and labels it "gamma_unmeasured" so nothing downstream
        # reports a dealer-positioning claim that was never measured.
        if not has_gamma:
            regime = "gamma_unmeasured"
        else:
            is_pos_gex = (s_t >= flip) and (net_gex >= 0)
            regime = "positive_gamma" if is_pos_gex else "negative_gamma"
            if abs(s_t - flip) <= 0.0025 * s_t:
                regime = "neutral_transition"

        action = "NONE"
        direction = "flat"
        setup_name = "None"
        conviction = 0.0
        stop_loss = 0.0
        take_profit = 0.0
        tp_1r = 0.0
        tp_2r = 0.0
        tp_3r = 0.0
        # "kernel" -> target the causal mean, clamped into the 1R-3R band.
        # "r2"     -> target 2R. Set by whichever branch fires.
        target_mode = "r2"
        charm_extend = False
        invalidation = ""
        notes = []

        # 0DTE Charm unhedging check: Afternoon session (e.g. index > 70% of day or timestamp has '14:'/'15:')
        is_afternoon = ("14:" in ts or "15:" in ts or (n >= 20 and t >= int(n * 0.7)))
        charm_melt_up_active = (
            enable_0dte_charm_override
            and is_afternoon
            and (net_chex > 0 or (net_gex is not None and net_gex > 0))
        )

        # Decision Tree.
        #
        # `mode` is what actually selects the branch: "revert" runs the
        # band-fade setups, "extend" the breakout setups. With gamma measured,
        # the regime picks it (long gamma dampens -> revert; short gamma
        # amplifies -> extend). Without gamma, kinematics pick it -- a velocity
        # z-score beyond the breakout threshold is the price-only evidence that
        # the tape is extending. Same setups either way; only the evidence for
        # choosing between them changes, and the ticket says which it was.
        if regime == "positive_gamma":
            mode = "revert"
        elif regime == "negative_gamma":
            mode = "extend"
        elif regime == "gamma_unmeasured":
            mode = "extend" if abs(v_z) > breakout_z else "revert"
        else:
            mode = "none"

        gamma_tag = "PosGEX" if regime == "positive_gamma" else "NegGEX" if regime == "negative_gamma" else "Kinematic"

        if mode == "revert":
            if c_wall is not None and p_wall is not None:
                topography_quadrant = "forward_positive_ramp" if c_wall - s_t <= s_t - p_wall else "backward_positive_ramp"
            else:
                topography_quadrant = "kinematic_range"

            # Long Setup: Touch/penetrate lower band with momentum stabilizing
            if (s_t <= lower_band or s_prev <= prev_low_band) and (v_z >= -0.6 or v_z > v_prev_z):
                action = "ENTER_LONG"
                direction = "long"
                setup_name = f"{gamma_tag}_LowerBand_Exhaustion"
                conviction = min(0.95, 0.72 + max(0.0, lower_band - s_t) / max(1e-4, sigma_loc))
                # Stop one bar-sigma beyond whichever is lower, spot or the band
                # being reverted from. The mean-reversion target is the kernel
                # mean, held inside the 1R-3R ladder so it stays a move the bar
                # volatility can actually produce.
                stop_loss = min(s_t, lower_band) - 1.0 * u
                target_mode = "kernel"
                invalidation = (
                    f"Spot closing below Gamma Flip ${flip:.2f} with negative acceleration"
                    if flip is not None
                    else "Spot closing below the lower envelope with negative acceleration"
                )
                notes.append(
                    "Positive GEX mean-reversion long; dealer put hedging creates supportive floor"
                    if regime == "positive_gamma"
                    else "Kinematic mean-reversion long at the lower envelope; no dealer-gamma read available"
                )
                if charm_melt_up_active:
                    charm_extend = True
                    notes.append("0DTE Charm melt-up active; extended take-profit target above standard VWAP")

            # Short Setup: Touch/penetrate upper band with upside stalling (and not strong bull trend)
            elif (s_t >= upper_band or s_prev >= prev_up_band) and (v_z <= 0.6 or v_z < v_prev_z) and not trend_up:
                if charm_melt_up_active:
                    notes.append("Short signal suppressed due to 0DTE afternoon Charm unhedging melt-up flow")
                else:
                    action = "ENTER_SHORT"
                    direction = "short"
                    setup_name = f"{gamma_tag}_UpperBand_Deceleration"
                    conviction = min(0.95, 0.72 + max(0.0, s_t - upper_band) / max(1e-4, sigma_loc))
                    stop_loss = max(s_t, upper_band) + 1.0 * u
                    target_mode = "kernel"
                    invalidation = (
                        f"Spot breaking above Call Wall ${c_wall:.2f} on accelerating volume"
                        if c_wall is not None
                        else "Spot breaking above the upper envelope on accelerating volume"
                    )
                    notes.append(
                        "Positive GEX mean-reversion short; dealer call hedging creates overhead resistance"
                        if regime == "positive_gamma"
                        else "Kinematic mean-reversion short at the upper envelope; no dealer-gamma read available"
                    )

        elif mode == "extend":
            if c_wall is not None and p_wall is not None:
                topography_quadrant = "forward_negative_slide" if s_t - p_wall <= c_wall - s_t else "backward_negative_slide"
            else:
                topography_quadrant = "kinematic_expansion"

            # Short Breakdown: Breach below lower band (or the put wall, when
            # one is measured) with strong negative kinematic acceleration.
            breached_down = s_t < lower_band or (p_wall is not None and s_t <= p_wall)
            breached_up = s_t > upper_band or (c_wall is not None and s_t >= c_wall)

            # Trend & Freshness Filters:
            # 1. Macro indices (SPY, QQQ, etc.) have strong structural upward drift and dealer put-support.
            #    Short breakdown cascades without confirmed negative gamma are prone to bear traps.
            # 2. Short breakdowns require alignment with trend (not trend_up) to avoid shorting dips in bull trends.
            # 3. Freshness: only trigger if breach occurred within the last 2 bars (not chasing exhausted moves).
            is_macro_index = symbol.upper() in {"SPY", "QQQ", "IWM", "DIA"}
            fresh_upper = (s_prev <= prev_up_band) or (t >= 2 and p[t - 2] <= nw_res.upper[t - 2])
            fresh_lower = (s_prev >= prev_low_band) or (t >= 2 and p[t - 2] >= nw_res.lower[t - 2])

            allow_short_cascade = (
                not (is_macro_index and regime == "gamma_unmeasured")
                and (not trend_up or regime == "negative_gamma")
                and (fresh_lower or p_wall is not None)
            )
            allow_long_expansion = (
                (trend_up or regime == "negative_gamma")
                and (fresh_upper or c_wall is not None)
            )

            if breached_down and v_z < -breakout_z and allow_short_cascade:
                action = "ENTER_SHORT"
                direction = "short"
                setup_name = f"{gamma_tag}_PutWall_Cascade" if p_wall is not None else f"{gamma_tag}_LowerBreak_Cascade"
                conviction = min(0.98, 0.75 + (abs(v_z) - breakout_z) * 0.1)
                # Breakdown: the risk is a reclaim of the level that broke,
                # capped at one bar-sigma so the stop stays a volatility
                # distance rather than a channel width. Target is 2R.
                stop_loss = min(s_t + 1.0 * u, max(s_t, lower_band) + 0.5 * u)
                target_mode = "r2"
                invalidation = (
                    f"False breakdown: Spot re-crossing above Gamma Flip ${flip:.2f}"
                    if flip is not None
                    else "False breakdown: Spot re-crossing above the kernel mean"
                )
                notes.append(
                    "Negative GEX breakdown cascade; dealer short-delta hedging accelerates selling"
                    if regime == "negative_gamma"
                    else "Kinematic breakdown on velocity expansion; no dealer-gamma read available"
                )

            # Long Short-Squeeze: Decisive breakout above the upper band (or the
            # call wall, when measured) with positive velocity.
            elif breached_up and v_z > breakout_z and allow_long_expansion:
                action = "ENTER_LONG"
                direction = "long"
                setup_name = f"{gamma_tag}_CallWall_ShortSqueeze" if c_wall is not None else f"{gamma_tag}_UpperBreak_Expansion"
                conviction = min(0.98, 0.75 + (v_z - breakout_z) * 0.1)
                stop_loss = max(s_t - 1.0 * u, min(s_t, upper_band) - 0.5 * u)
                target_mode = "r2"
                invalidation = (
                    f"False breakout: Spot re-crossing below Call Wall ${c_wall:.2f}"
                    if c_wall is not None
                    else "False breakout: Spot re-crossing below the kernel mean"
                )
                notes.append(
                    "Negative GEX short-squeeze; dealer short-covering and positive vanna kick accelerate rally"
                    if regime == "negative_gamma"
                    else "Kinematic breakout on velocity expansion; no dealer-gamma read available"
                )
        else:
            topography_quadrant = "transition_zone"

        # One R is the distance to the stop actually quoted on this ticket --
        # the standard definition -- so "2R" on the ladder is genuinely twice
        # what the trade loses if it is wrong, and risk_reward below is exact
        # rather than an approximation of a sigma multiple.
        stop_dist = abs(s_t - stop_loss) if action in {"ENTER_LONG", "ENTER_SHORT"} else 0.0
        if stop_dist > 1e-9:
            sign = 1.0 if direction == "long" else -1.0
            tp_1r = s_t + sign * stop_dist
            tp_2r = s_t + sign * 2.0 * stop_dist
            tp_3r = s_t + sign * 3.0 * stop_dist
            if target_mode == "kernel":
                # Revert to the causal mean, but never book a target the bar
                # volatility cannot reach, nor one inside 1R.
                take_profit = (
                    min(max(k_mean, tp_1r), tp_3r) if direction == "long"
                    else max(min(k_mean, tp_1r), tp_3r)
                )
            else:
                take_profit = tp_2r
            if charm_extend:
                take_profit = (
                    min(take_profit + 0.5 * u, tp_3r) if direction == "long"
                    else max(take_profit - 0.5 * u, tp_3r)
                )

        # Position size is solved from the stop, not scaled off conviction.
        # `conviction * 10` put 8.4% of capital behind an 84%-conviction ticket
        # no matter how far the stop was, so an unusually wide stop silently
        # multiplied the loss it was sized against. Conviction now sets the risk
        # budget (0.25%-1.00% of capital) and the stop distance decides how much
        # notional that budget buys.
        if stop_dist > 1e-9 and s_t > 0:
            risk_budget_pct = 0.25 + 0.75 * conviction
            # MAX_SINGLE_NAME_PCT caps concentration: a very tight stop would
            # otherwise solve to a position larger than the book should hold in
            # one name, however small the loss at the stop.
            size_pct = min(MAX_SINGLE_NAME_PCT, risk_budget_pct * s_t / stop_dist)
            reward_risk = abs(take_profit - s_t) / stop_dist
        else:
            size_pct = 0.0
            reward_risk = 0.0

        sig = ExecutionSignal(
            bar_index=t,
            timestamp=ts,
            symbol=symbol,
            action=action,
            direction=direction,
            price=round(s_t, 2),
            regime=regime,
            topography_quadrant=topography_quadrant,
            setup_name=setup_name,
            conviction=round(conviction, 3),
            suggested_size_pct=round(size_pct, 1),
            entry_price=round(s_t, 2),
            stop_loss=round(stop_loss, 2),
            take_profit=round(take_profit, 2),
            invalidation_anchor=invalidation,
            kalman_velocity=round(v_k, 4),
            kalman_zscore=round(v_z, 3),
            kernel_mean=round(k_mean, 2),
            upper_envelope=round(upper_band, 2),
            lower_envelope=round(lower_band, 2),
            anchored_vwap=round(vwap_t, 2),
            call_wall=round(c_wall, 2) if c_wall is not None else None,
            put_wall=round(p_wall, 2) if p_wall is not None else None,
            gamma_flip=round(flip, 2) if flip is not None else None,
            risk_unit=round(u, 4),
            risk_unit_basis=risk_basis,
            risk_reward=round(reward_risk, 2),
            target_1r=round(tp_1r, 2),
            target_2r=round(tp_2r, 2),
            target_3r=round(tp_3r, 2),
            notes=notes,
        )
        signals.append(sig)

    return signals, nw_res, kalman_res, vwap_results


# ---------------------------------------------------------------------------
# Microstructure Backtest Simulator
# ---------------------------------------------------------------------------

def run_microstructure_backtest(
    prices: Sequence[float] | np.ndarray,
    *,
    timestamps: Sequence[str] | None = None,
    symbol: str = "SPY",
    volumes: Sequence[float] | np.ndarray | None = None,
    highs: Sequence[float] | np.ndarray | None = None,
    lows: Sequence[float] | np.ndarray | None = None,
    gamma_flip_series: Sequence[float] | np.ndarray | None = None,
    call_wall_series: Sequence[float] | np.ndarray | None = None,
    put_wall_series: Sequence[float] | np.ndarray | None = None,
    net_gex_series: Sequence[float] | np.ndarray | None = None,
    net_chex_series: Sequence[float] | np.ndarray | None = None,
    iv_series: Sequence[float] | np.ndarray | None = None,
    initial_capital: float = 100_000.0,
    risk_per_trade_pct: float = 0.02,   # 2% cash risk per trade
    max_position_pct: float = 0.15,     # Max 15% position notional cap (MAX_SINGLE_NAME_PCT)
    slippage_bps: float = 2.0,          # 2 bps half-spread slippage
    commission_per_share: float = 0.005,# $0.005 per share
    max_holding_bars: int = 30,
    enable_delta_hedging: bool = False,
) -> BacktestTearsheet:
    """Run full sequential event-driven backtest over historical microstructure signals.

    Args:
        prices: Underlying bar prices.
        timestamps: Bar timestamps.
        symbol: Ticker symbol.
        volumes: Bar volumes.
        gamma_flip_series: Zero gamma flip price per bar.
        call_wall_series: Call wall price per bar.
        put_wall_series: Put wall price per bar.
        net_gex_series: Net GEX ($M) per bar.
        net_chex_series: Net CHEX ($M) per bar.
        iv_series: Implied volatility per bar.
        initial_capital: Starting portfolio equity ($).
        risk_per_trade_pct: Risk budget per trade.
        slippage_bps: Execution slippage in basis points.
        commission_per_share: Fixed commission per share.
        max_holding_bars: Maximum time horizon before forced exit.
        enable_delta_hedging: If True, computes delta-hedging rebalancing cost.

    Returns:
        BacktestTearsheet containing trade log, equity curve, drawdown, and statistical metrics.
    """
    signals, nw_res, kalman_res, vwap_results = generate_microstructure_signals(
        prices,
        timestamps=timestamps,
        symbol=symbol,
        volumes=volumes,
        highs=highs,
        lows=lows,
        gamma_flip_series=gamma_flip_series,
        call_wall_series=call_wall_series,
        put_wall_series=put_wall_series,
        net_gex_series=net_gex_series,
        net_chex_series=net_chex_series,
        iv_series=iv_series,
    )

    n = len(prices)
    if n == 0:
        return BacktestTearsheet(
            symbol=symbol, n_bars=0, start_date="", end_date="", initial_capital=initial_capital,
            ending_capital=initial_capital, total_net_pnl=0.0, total_return_pct=0.0, cagr_pct=0.0,
            sharpe_ratio=0.0, sortino_ratio=0.0, calmar_ratio=0.0, max_drawdown_pct=0.0,
            max_drawdown_dollar=0.0, win_rate=0.0, profit_factor=0.0, expectancy_per_trade=0.0,
            total_trades=0, winning_trades=0, losing_trades=0, avg_win_dollar=0.0, avg_loss_dollar=0.0,
            win_loss_ratio=0.0, avg_holding_bars=0.0, total_slippage=0.0, total_commissions=0.0,
            total_gamma_pnl=0.0, total_hedging_pnl=0.0, daily_turnover_pct=0.0,
            equity_curve=[], drawdown_curve=[], trades=[], regime_breakdown={},
        )

    ts_list = list(timestamps) if timestamps is not None and len(timestamps) == n else [f"Bar_{i}" for i in range(n)]
    capital = initial_capital
    peak_capital = initial_capital
    trades: list[SimulatedTrade] = []
    trade_id_counter = 1

    active_trade: dict[str, Any] | None = None
    equity_curve: list[dict[str, Any]] = []
    drawdown_curve: list[dict[str, Any]] = []

    total_slippage = 0.0
    total_commissions = 0.0
    total_gamma_pnl = 0.0
    total_hedge_pnl = 0.0
    traded_notional = 0.0

    for t in range(n):
        s_t = float(prices[t])
        sig = signals[t]
        ts = ts_list[t]

        # 1. Manage Active Position (Exits & Trailing Stops)
        if active_trade is not None:
            dir_mult = 1.0 if active_trade["direction"] == "long" else -1.0
            holding_len = t - active_trade["entry_bar"]
            cur_unrealized_pnl = (s_t - active_trade["entry_price"]) * active_trade["shares"] * dir_mult
            risk_r = active_trade["risk_r"]

            # Dynamic Trailing Stop Ratcheting
            if active_trade["direction"] == "long":
                gain_r = (s_t - active_trade["entry_price"]) / risk_r
                if gain_r >= 1.0:
                    active_trade["stop_loss"] = max(active_trade["stop_loss"], active_trade["entry_price"] + 0.35 * risk_r)
                if gain_r >= 2.0:
                    active_trade["stop_loss"] = max(active_trade["stop_loss"], active_trade["entry_price"] + 1.25 * risk_r)
            else:
                gain_r = (active_trade["entry_price"] - s_t) / risk_r
                if gain_r >= 1.0:
                    active_trade["stop_loss"] = min(active_trade["stop_loss"], active_trade["entry_price"] - 0.35 * risk_r)
                if gain_r >= 2.0:
                    active_trade["stop_loss"] = min(active_trade["stop_loss"], active_trade["entry_price"] - 1.25 * risk_r)

            exit_reason = None
            # Take Profit hit
            if active_trade["direction"] == "long" and s_t >= active_trade["take_profit"]:
                exit_reason = "take_profit"
            elif active_trade["direction"] == "short" and s_t <= active_trade["take_profit"]:
                exit_reason = "take_profit"
            # Stop Loss hit (or trailing stop hit)
            elif active_trade["direction"] == "long" and s_t <= active_trade["stop_loss"]:
                exit_reason = "trailing_stop" if active_trade["stop_loss"] > active_trade["entry_price"] else "stop_loss"
            elif active_trade["direction"] == "short" and s_t >= active_trade["stop_loss"]:
                exit_reason = "trailing_stop" if active_trade["stop_loss"] < active_trade["entry_price"] else "stop_loss"
            # Invalidation: Spot crossed gamma flip against direction
            elif (
                active_trade["regime"] == "positive_gamma"
                and active_trade["direction"] == "long"
                and sig.gamma_flip is not None
                and s_t < sig.gamma_flip
                and sig.kalman_zscore < -1.4
            ):
                exit_reason = "invalidation"
            # Time exit with profit locking after 15 bars
            elif holding_len >= 15 and ((active_trade["direction"] == "long" and s_t >= active_trade["entry_price"]) or (active_trade["direction"] == "short" and s_t <= active_trade["entry_price"])):
                exit_reason = "time_profit"
            # Max holding horizon
            elif holding_len >= max_holding_bars:
                exit_reason = "time_horizon"
            # End of series forced close
            elif t == n - 1:
                exit_reason = "session_close"

            if exit_reason is not None:
                # Execute exit fill with slippage
                exit_slip = s_t * (slippage_bps / 10_000.0)
                fill_exit = s_t - exit_slip if active_trade["direction"] == "long" else s_t + exit_slip
                exit_comm = active_trade["shares"] * commission_per_share

                gross_pnl = (fill_exit - active_trade["entry_price"]) * active_trade["shares"] * dir_mult
                trade_slip_cost = (exit_slip + active_trade["entry_slip"]) * active_trade["shares"]
                trade_comm_cost = exit_comm + active_trade["entry_comm"]
                net_pnl = gross_pnl - exit_comm

                # Gamma PnL attribution
                gamma_attr = gross_pnl * (0.35 if active_trade["regime"] == "negative_gamma" else 0.15)
                hedge_cost = (abs(gross_pnl) * 0.05) if enable_delta_hedging else 0.0

                capital += net_pnl
                total_slippage += trade_slip_cost
                total_commissions += trade_comm_cost
                total_gamma_pnl += gamma_attr
                total_hedge_pnl -= hedge_cost
                traded_notional += (fill_exit * active_trade["shares"])

                completed_trade = SimulatedTrade(
                    trade_id=active_trade["trade_id"],
                    symbol=symbol,
                    direction=active_trade["direction"],
                    regime=active_trade["regime"],
                    setup_name=active_trade["setup_name"],
                    entry_bar=active_trade["entry_bar"],
                    entry_time=active_trade["entry_time"],
                    entry_price=round(active_trade["entry_price"], 2),
                    exit_bar=t,
                    exit_time=ts,
                    exit_price=round(fill_exit, 2),
                    exit_reason=exit_reason,
                    shares=round(active_trade["shares"], 2),
                    gross_pnl=round(gross_pnl, 2),
                    net_pnl=round(net_pnl, 2),
                    return_pct=round((net_pnl / max(1.0, active_trade["entry_price"] * active_trade["shares"])) * 100.0, 2),
                    holding_bars=holding_len,
                    slippage_cost=round(trade_slip_cost, 2),
                    transaction_cost=round(trade_comm_cost, 2),
                    gamma_pnl_attribution=round(gamma_attr, 2),
                    delta_hedge_cost=round(hedge_cost, 2),
                )
                trades.append(completed_trade)
                active_trade = None

        # 2. Check for New Entry Signal
        if active_trade is None and sig.action in {"ENTER_LONG", "ENTER_SHORT"} and t < n - 1:
            risk_dollars = capital * risk_per_trade_pct
            price_dist_to_stop = max(0.5, abs(s_t - sig.stop_loss))
            shares = max(1.0, risk_dollars / price_dist_to_stop)
            # Cap position notional at max_position_pct of capital
            max_shares = (capital * max_position_pct) / s_t
            shares = min(shares, max_shares)

            entry_slip = s_t * (slippage_bps / 10_000.0)
            fill_entry = s_t + entry_slip if sig.direction == "long" else s_t - entry_slip
            entry_comm = shares * commission_per_share

            traded_notional += (fill_entry * shares)

            active_trade = {
                "trade_id": trade_id_counter,
                "direction": sig.direction,
                "regime": sig.regime,
                "setup_name": sig.setup_name,
                "entry_bar": t,
                "entry_time": ts,
                "entry_price": fill_entry,
                "entry_slip": entry_slip,
                "entry_comm": entry_comm,
                "stop_loss": sig.stop_loss,
                "take_profit": sig.take_profit,
                "shares": shares,
                "risk_r": price_dist_to_stop,
            }
            trade_id_counter += 1

        # Track Equity & Drawdown
        peak_capital = max(peak_capital, capital)
        dd_dollar = peak_capital - capital
        dd_pct = (dd_dollar / peak_capital) * 100.0 if peak_capital > 0 else 0.0

        equity_curve.append({
            "bar": t,
            "timestamp": ts,
            "equity": round(capital, 2),
            "spot": s_t,
        })
        drawdown_curve.append({
            "bar": t,
            "timestamp": ts,
            "drawdown_pct": round(dd_pct, 3),
            "drawdown_dollar": round(dd_dollar, 2),
        })

    # 3. Calculate Summary Statistics
    total_net_pnl = capital - initial_capital
    total_return_pct = (total_net_pnl / initial_capital) * 100.0
    n_trades = len(trades)
    winning_trades = [tr for tr in trades if tr.net_pnl > 0]
    losing_trades = [tr for tr in trades if tr.net_pnl <= 0]
    n_wins = len(winning_trades)
    n_losses = len(losing_trades)
    win_rate = (n_wins / n_trades * 100.0) if n_trades > 0 else 0.0

    gross_wins = sum(tr.net_pnl for tr in winning_trades)
    gross_losses = abs(sum(tr.net_pnl for tr in losing_trades))
    profit_factor = (gross_wins / gross_losses) if gross_losses > 0 else (99.0 if gross_wins > 0 else 0.0)

    avg_win = (gross_wins / n_wins) if n_wins > 0 else 0.0
    avg_loss = (gross_losses / n_losses) if n_losses > 0 else 0.0
    win_loss_ratio = (avg_win / avg_loss) if avg_loss > 0 else 0.0
    expectancy = (total_net_pnl / n_trades) if n_trades > 0 else 0.0
    avg_holding = (sum(tr.holding_bars for tr in trades) / n_trades) if n_trades > 0 else 0.0

    # Max Drawdown
    max_dd_pct = max((d["drawdown_pct"] for d in drawdown_curve), default=0.0)
    max_dd_dollar = max((d["drawdown_dollar"] for d in drawdown_curve), default=0.0)

    # Returns & Sharpe calculation
    eq_series = pd.Series([d["equity"] for d in equity_curve])
    pct_returns = eq_series.pct_change().dropna()
    mean_ret = pct_returns.mean()
    std_ret = pct_returns.std(ddof=1)
    # Annualized with 252 factor
    sharpe = float((mean_ret / std_ret * math.sqrt(252.0))) if std_ret > 1e-8 else 0.0

    # Sortino (downside deviation)
    downside_returns = pct_returns[pct_returns < 0]
    downside_std = downside_returns.std(ddof=1)
    sortino = float((mean_ret / downside_std * math.sqrt(252.0))) if downside_std > 1e-8 else 0.0

    # Calmar Ratio
    calmar = (total_return_pct / max_dd_pct) if max_dd_pct > 0 else 0.0
    cagr = ((capital / initial_capital) ** (252.0 / max(1, n)) - 1.0) * 100.0

    # Daily Turnover
    daily_turnover_pct = (traded_notional / (initial_capital * max(1, n / 252.0))) * 100.0

    # 4. Regime-Segmented Tearsheet
    regimes = ["positive_gamma", "negative_gamma", "neutral_transition"]
    regime_breakdown: dict[str, RegimeMetrics] = {}
    for reg in regimes:
        reg_trades = [tr for tr in trades if tr.regime == reg]
        reg_n = len(reg_trades)
        if reg_n > 0:
            reg_wins = len([tr for tr in reg_trades if tr.net_pnl > 0])
            reg_win_rate = (reg_wins / reg_n) * 100.0
            reg_pnl = sum(tr.net_pnl for tr in reg_trades)
            reg_gross_w = sum(tr.net_pnl for tr in reg_trades if tr.net_pnl > 0)
            reg_gross_l = abs(sum(tr.net_pnl for tr in reg_trades if tr.net_pnl <= 0))
            reg_pf = (reg_gross_w / reg_gross_l) if reg_gross_l > 0 else 99.0
            reg_avg_ret = sum(tr.return_pct for tr in reg_trades) / reg_n
            reg_metrics = RegimeMetrics(
                regime_name=reg,
                n_trades=reg_n,
                win_rate=round(reg_win_rate, 2),
                profit_factor=round(reg_pf, 2),
                total_net_pnl=round(reg_pnl, 2),
                avg_return_pct=round(reg_avg_ret, 2),
                sharpe_ratio=round(reg_avg_ret / (abs(reg_avg_ret) + 1.0), 2),
            )
        else:
            reg_metrics = RegimeMetrics(
                regime_name=reg,
                n_trades=0,
                win_rate=0.0,
                profit_factor=0.0,
                total_net_pnl=0.0,
                avg_return_pct=0.0,
                sharpe_ratio=0.0,
            )
        regime_breakdown[reg] = reg_metrics

    return BacktestTearsheet(
        symbol=symbol,
        n_bars=n,
        start_date=ts_list[0],
        end_date=ts_list[-1],
        initial_capital=round(initial_capital, 2),
        ending_capital=round(capital, 2),
        total_net_pnl=round(total_net_pnl, 2),
        total_return_pct=round(total_return_pct, 2),
        cagr_pct=round(cagr, 2),
        sharpe_ratio=round(sharpe, 2),
        sortino_ratio=round(sortino, 2),
        calmar_ratio=round(calmar, 2),
        max_drawdown_pct=round(max_dd_pct, 2),
        max_drawdown_dollar=round(max_dd_dollar, 2),
        win_rate=round(win_rate, 2),
        profit_factor=round(profit_factor, 2),
        expectancy_per_trade=round(expectancy, 2),
        total_trades=n_trades,
        winning_trades=n_wins,
        losing_trades=n_losses,
        avg_win_dollar=round(avg_win, 2),
        avg_loss_dollar=round(avg_loss, 2),
        win_loss_ratio=round(win_loss_ratio, 2),
        avg_holding_bars=round(avg_holding, 1),
        total_slippage=round(total_slippage, 2),
        total_commissions=round(total_commissions, 2),
        total_gamma_pnl=round(total_gamma_pnl, 2),
        total_hedging_pnl=round(total_hedge_pnl, 2),
        daily_turnover_pct=round(daily_turnover_pct, 2),
        equity_curve=equity_curve,
        drawdown_curve=drawdown_curve,
        trades=trades,
        regime_breakdown=regime_breakdown,
    )
